AWSTemplateFormatVersion: "2010-09-09"
Description: "Pipeline to build, test, and deploy the qtest-collection JVM artifacts to Maven Central"

Parameters:
  GitHubPersonalAccessToken:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/qtest-library-pipeline/github-access-token'
  GitHubOwner:
    Type: String
    Default: paul-nelson-baker
  GitHubRepo:
    Type: String
    Default: qtest-library-collection
  GitHubBranch:
    Type: String
    Default: master

Resources:
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: QTest Library Pipeline
      Stages:
        - Name: GitHub Source Repository
          ActionTypeId:
            Category: Source
            Owner: !Ref GitHubOwner
            Repo: !Ref GitHubRepo
            Branch: !Ref GitHubBranch
            OAuthToken: !Ref GitHubPersonalAccessToken
