AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Pipeline to build, test, and deploy the qtest-collection
  JVM artifacts to Maven Central

Parameters:
  GitHubPersonalAccessToken:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/qtest-library-pipeline/github-access-token'
  GitHubOwner:
    Type: String
    Default: paul-nelson-baker
  GitHubRepo:
    Type: String
    Default: qtest-library-collection
  GitHubBranch:
    Type: String
    Default: master
  S3ArtifactBucket:
    Type: String
    Default: paulbaker-artifacts
  S3ArtifactDirectory:
    Type: String
    Default: ephemeral-codebuild-items

Resources:
  CodeBuildProjectRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action: "sts:AssumeRole"

  CodePipelineAccessRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "codepipeline.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"

  CodePipelineAccessRolePolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      Roles:
        - "Ref": CodePipelineAccessRole
      PolicyName: CodePipelineAccessRolePolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - "s3:ListBucket"
            Resource:
              - "Fn::Join": ["", ["arn:aws:s3:::", !Ref S3ArtifactBucket]]
          - Effect: Allow
            Action:
              - "s3:GetObject"
              - "s3:PutObject"
              - "s3:DeleteObject"
            Resource:
              - "Fn::Join": ["", ["arn:aws:s3:::", !Ref S3ArtifactBucket, "/*"]]
          - Effect: Allow
            Action:
              - "codecommit:GetBranch"
              - "codecommit:GetCommit"
              - "codecommit:UploadArchive"
              - "codecommit:GetUploadArchiveStatus"
              - "codecommit:CancelUploadArchive"
            Resource: "*"

  JavaCodeBuildProject:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Name: !Ref GitHubRepo
      Description: !Join ["", ["The codebuild project that builds the JVM artifacts for ", !Ref GitHubRepo]]
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/java:openjdk-8
      ServiceRole: !Ref CodeBuildProjectRole
      Source:
        Type: CODEPIPELINE
      Artifacts:
        Type: CODEPIPELINE

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: "qtest-library-pipeline"
      ArtifactStore:
        Type: S3
        Location:
          !Ref S3ArtifactBucket
      RoleArn:
        !GetAtt [CodePipelineAccessRole, "Arn"]
      Stages:
        - Name: !Join ["-", [!Ref GitHubRepo, "source"]]
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubPersonalAccessToken
              OutputArtifacts:
                - Name: SourceCodeArtifact
              RunOrder: 1
        - Name: !Join ["-", [!Ref GitHubRepo, "build"]]
          Actions:
            - Name: Build
              InputArtifacts:
                  - Name: SourceCodeArtifact
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref GitHubRepo
              OutputArtifacts:
                  - Name: JavaBinaryArtifact
              RunOrder: 2
